#!/bin/bash
echo "Hello, World"

vim 1-confused_smiley
#!/bin/bash
echo"\"(Ôo)"""

vim 2-hellofile
#!/bin/nash
cat /etc/passwd

vim 3-twofiles
#!/bin/bash
cat etc/passwd /etc/hosts

vim 4-lastlines
#!/bin/bash
tail -n 10 etc/passwd

vim 5-firstlines
#!/bin/bash
head -n 10 etc/passwd

chmod u+x 0-h
